### ISSUE TITLE
add GoogleChrome/lighthouse module

### ISSUE THREAD

**Issue by derekperkins** [bufbuild/modules#78]
## Mandatory

**Where is the source code for the Managed Module?**

https://github.com/GoogleChrome/lighthouse/blob/main/proto/lighthouse-result.proto

## Optional

**Does this module have other module dependencies/imports?**

```
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
```

**Do you think this module is widely used by the community, and is not already provided on the BSR by the owners?**

Not sure how many people are interacting with the Lighthouse proto directly, but in general, demand for headless Chrome via Puppeteer and other methods is growing.

**Comment by bufdev** [comment]
We can add this one. Approved. Call it buf.build/googlechrome/lighthouse.

**Comment by derekperkins** [comment]
cc @mordfustang21

**Comment by unmultimedio** [comment]
I'll start working on this. I'm thinking to set it to start syncing from latest commit on main as of today, and then all main commits onwards. Or any specific commit to use as initial reference? cc @bufdev @pgmitche

**Comment by derekperkins** [comment]
We don't have a preference, latest is great

**Comment by unmultimedio** [comment]
Thanks for the wait on this. During testing of this sync we discovered that the file [does not define a Protobuf package](https://github.com/GoogleChrome/lighthouse/blob/e713de194f49b5cfd2fa67957439298ef321edd8/proto/lighthouse-result.proto#L1-L9). We are sorry, we should have caught this earlier.

![image](https://github.com/bufbuild/modules/assets/4431392/657d00c9-79e1-4314-ad70-173611cb2935)

Sadly we cannot sync this module. While not declaring a Protobuf package is valid syntax, the BSR considers this a malformed Protobuf definition since a lot of its functionalities are based on the existence of such packages.

We recommend:
- You could send an upstream PR to the original repository, and once the package is defined correctly in the source code, we can pick it up again.
- You could vendor the file in your BSR modules, and embed it in one of your Protobuf packages.

**Comment by derekperkins** [comment]
upstream patch submitted
https://github.com/GoogleChrome/lighthouse/issues/15115
https://github.com/GoogleChrome/lighthouse/pull/15116

**Comment by derekperkins** [comment]
That merged, so we should be able to reopen this

**Comment by unmultimedio** [comment]
Thanks for the upstream patch! I will pick up this work again next week.

**Comment by unmultimedio** [comment]
@derekperkins probably something that we'll need is that the repo publishes an stable semver release with this new version of the file. This is so we're able to sync tagged releases instead of individual git references.

**Comment by unmultimedio** [comment]
Hello @derekperkins, this module is already available at https://buf.build/googlechrome/lighthouse, thanks for the wait, I was trying to give a little room to see if they cut an stable semver release soon, but they haven't, so in the meantime we're just syncing all git commit SHAs in the `main` branch. I've left a TODO once they do new releases, to switch our sync to semver releases again.

Closing as resolved.

**Comment by derekperkins** [comment]
Awesome, thanks for your help @unmultimedio!
